.TH man 1 "04 May 2016" "1.0" "burst man page"
.SH NAME
burst
.SH SYNOPSIS
burst [OPTION]... [FILE]...
.SH DESCRIPTION
burst is high level shell program for splitting a file into segments. The result will be multiple files with the max number of lines as defined by the user (default is 500).
.SH OPTIONS
.B
-l, \-\-lines
.RS	
Number of lines per output file
.SH BUGS
No known bugs.
.SH AUTHOR
Eric Svonavec (eps8@zips.uakron.edu)
